spring.boot:
    admin.url: http://localhost:8080

management:
    security.enabled: false

app:

    activemq:
        host: localhost
        port: 61616
        username: admin
        password: admin
